on:
  workflow_dispatch:
    inputs:
      yes-no-answer:
        description: 'Say yes or no'
        required: true

jobs:
  job-A:
    runs-on: ubuntu-latest
    steps:
      - name: Validate
        run: |
          echo "VALID=${{ github.event.inputs.yes-no-answer == 'yes' || github.event.inputs.yes-no-answer == 'no' }}" >> $GITHUB_ENV

      - name: Abort if invalid
        if: '!fromJSON(env.VALID)'
        run: |
          echo "::error::Something went wrong"
          exit 1
      - name: Report value of VALID
        run: |
          echo "VALID = ${{ env.VALID }}"
          echo "VALID = $VALID"
