on:
  push:

jobs:
  job-A:
    runs-on: ubuntu-latest
    steps:
      - name: First
        run: |
          echo "::error::Something went wrong"
          exit 1
      - name: Second
        run: |
          echo "We got to the second step."
