# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions

name: Test some things

on:
  push:
  workflow_dispatch:

env:
  # Note that checks against these values will all be case insensitive!
  a: '{ yes-values: ["yes", "y"], no-values: ["no", "n"] }'

jobs:
  get_vars:
    runs-on: ubuntu-latest
    env:
      b: ${{ toJSON(fromJSON(env.a).*.* }}
      c: ${{ toJSON(fromJSON(env.a).yes-values }}
      d: ${{ toJSON(fromJSON(env.a).no-values.* }}
    steps:
      - name: Print varsValidate Input
        run: |
          echo ${{ env.a }}
          echo ${{ env.b }}
          echo ${{ env.c }}
          echo ${{ env.d }}
          