on: 
  - push
  - workflow_dispatch

jobs:
  example-job:
    runs-on: macOS-latest

    steps:
      - name: Retrieve secret
        env:
          SUPER_SECRET: ${{ secrets.SUPERSECRET }}
        run: |
          echo "$SUPER_SECRET"
