on: 
  - push
  - workflow_dispatch

jobs:
  example-job:
    runs-on: macOS-latest

    steps:
      - name: Retrieve secret
        env:
          SUPER_SECRET: ${{ secrets.SUPERSECRET }}
          secret: "we're on a branch now"
        run: |
          echo "THIS IS MY SECRET: $SUPER_SECRET"
          echo $secret
