on:
  workflow_dispatch:

jobs:
  job-A:
    runs-on: ubuntu-latest

    steps:

    # Checks out this repository under $GITHUB_WORKSPACE/source:

    - name: 1. Check out master
      uses: actions/checkout@v2
      with:
        path: source

    - name: 2. Run Make
      run: |
        cd source
        make

    - name: 3. Run Make using action
      uses: ./source/.github/actions/doxygen-action
      with:
        # Working directory
        working-directory: "source/doxygen"

    - name: 4. Display result page
      run: |
        cat source/doxygen/doxygen_docs_complete/html/page3.html
