# See https://stackoverflow.com/questions/65384420/how-to-make-a-github-action-matrix-element-conditional

name: Configurable Build Matrix

on:
  push:
  workflow_dispatch:
    inputs:
      check-windows:
        description: 'Test build on Windows'
        required: false
        default: 'true'
      check-mac:
        description: 'Test build on MacOS'
        required: false
        default: 'true'
      check-r-release-version-on-ubuntu:
        description: 'Check on Ubuntu using the release version of R'
        required: false
        default: 'true'
      check-r-devel-version-on-ubuntu:
        description: 'Check on Ubuntu using the development version of R'
        required: false
        default: 'true'

jobs:
  matrix_prep:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: set-matrix
        name: Conditional Build Matrix
        uses: JoshuaTheMiller/conditional-build-matrix@0.0.1
        with:          
          filter: |
            '[?contains(runOnEvent,`${{ github.event_name }}`) ||

               (`${{ github.event.inputs.check-windows }}` == `"true"` &&
                contains(os, `"windows"`)) ||

               (`${{ github.event.inputs.check-mac }}` == `"true"` &&
                contains(os, `"macOS"`)) ||

               (contains(os, `"ubuntu"`) &&

                ((`${{ github.event.inputs.check-r-release-version-on-ubuntu }}` == `"true"` &&
                  contains(r, `"release"`)) ||

                 (`${{ github.event.inputs.check-r-devel-version-on-ubuntu }}` == `"true"` &&
                  contains(r, `"devel"`))))]'

  build-n-test:
    needs: matrix_prep
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJson(needs.matrix_prep.outputs.matrix)}}
    steps:
    - name: Report Configuration
      env:
        MATRIX_CONTEXT: ${{ toJSON(matrix) }}
      run: |
        echo "os: " ${{ matrix.os }}
        echo "matrix: $MATRIX_CONTEXT"
