name: Test Environment Variable Usage

on:
  workflow_dispatch:
    inputs:
      a:
        description: 'Enter a number from 1 to 4:'
        required: false
        default: '4'

jobs:
  strategy:
    matrix:
      include:
        - b: 1
        - b: 2
        - b: 3
        - b: 4
  variable-passing:
    name: Variable Passing with b = ${{ matrix.b }}

    runs-on: ubuntu-latest


    steps:
      - name: Set Enviroment Variable
        run: |
          echo "EQ=${{ strategy.matrix.b == github.events.inputs.a }}" >> $GITHUB_ENV
      
      - name: Use Environment Variable
        if: env.EQ == true
        run: echo "The input equals the b matrix value."

      - name: Direct Usage
        if: (strategy.matrix.b == github.events.inputs.a) == true
        run: echo "The input equals the b matrix value."
      