name: Test Environment Variable Usage

on:
  push:
  workflow_dispatch:
    inputs:
      a:
        description: 'Enter a number from 1 to 4:'
        required: false
        default: '4'

jobs:
  variable-passing:
    strategy:
      matrix:
        b: [1, 2, 3, 4]

    name: Variable Passing with b = ${{ matrix.b }}

    runs-on: ubuntu-latest

    steps:
      - name: Set Enviroment Variable
        run: |
          echo "EQ=${{ matrix.b == github.events.inputs.a }}" >> $GITHUB_ENV
      
      - name: Use Environment Variable
        if: env.EQ == 'true'
        run: |
          echo "The input equals the b matrix value."
          echo "The value of EQ is ${{ env.EQ }}."
      - name: Direct Usage
        if: (matrix.b == github.events.inputs.a) == true
        run: |
          echo "The input equals the b matrix value."
          echo "The value of EQ is ${{ env.EQ }}."
      - name: Debug
        run: |
          echo "EQ = $EQ"
          echo "The value of EQ is ${{ env.EQ }}."
          echo "matrix b = ${{ matrix.b }}."
          echo "github.events.inputs.a = ${{ github.events.inputs.a }}."
      