name: Test Environment Variable Usage

on:
  workflow_dispatch:
    inputs:
      a:
        description: 'Enter a number from 1 to 4:'
        required: false
        default: '4'

jobs:
  strategy:
    matrix:
      include:
        - b: 1
        - b: 2
        - b: 3
        - b: 4
  variable-passing:
    runs-on: ubuntu-latest

    env:
      EQ: strategy.matrix.b == github.events.inputs.a

    steps:
      - name: Use Environment Variable
        if: env.EQ == '3'
        run: echo "The input equals the b matrix value."

      - name: Direct Usage
        if: github.event.inputs.a == '3'
        run: echo "The input equals the b matrix value."
      