name: Test Environment Variable Usage

on:
  #push:
  workflow_dispatch:
    inputs:
      check-windows:
        description: 'Test build on Windows'
        required: false
        default: 'false'
      check-mac:
        description: 'Test build on MacOS'
        required: false
        default: 'false'
      check-r-release-version-on-ubuntu:
        description: 'Check on Ubuntu using the release version of R'
        required: false
        default: 'false'
      check-r-devel-version-on-ubuntu:
        description: 'Check on Ubuntu using the development version of R'
        required: false
        default: 'false'

jobs:
  ## strategy:
  ##   matrix:
  ##     b: [1, 2, 3, 4]
  variable-passing:
    runs-on: ubuntu-latest

    env:
      ## EQ: strategy.matrix.b == github.events.inputs.a
      EQ: ${{ github.events.inputs.a }}

    steps:
      - name: Use Environment Variable
        if: env.EQ == 3
        run: echo "The input equals the b matrix value."
