on: 
  push:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: windows-latest

    steps:
      - name: Set var
        run: |
          echo "NEED_TINYTEX=true" >> $GITHUB_ENV
      - name: Install TinyTex
        if: env.NEED_TINYTEX == 'true'
        run: |
          echo "(Install TinyTex)"
      - name: View NEED_TINYTEX
        run: |
          echo "${{ env.NEED_TINYTEX }}"
          echo "$NEED_TINYTEX"
          echo $GITHUB_ENV

  example-from-workflow-docs:
    runs-on: windows-latest
    steps:
      - name: Set the value
        id: step_one
        run: |
            echo "action_state=yellow" >> $GITHUB_ENV
      - name: Use the value
        id: step_two
        run: |
            echo "${{ env.action_state }}" # This will output 'yellow'

  setter-1:
    runs-on: ubuntu-latest
    steps:
      - name: Set var
        run: |
          echo "NEED_TINYTEX=true" >> $GITHUB_ENV
          echo $GITHUB_ENV
          echo $NEED_TINYTEX

  getter-1:
    runs-on: ubuntu-latest
    steps:
      - name: get using ubuntu
        run: |
          echo $GITHUB_ENV
          echo $NEED_TINYTEX

  setter-2:
    runs-on: ubuntu-latest
    outputs:
      need-tinytex: ${{ steps.set_outputs.outputs.need-tinytex }}
    steps:
      - name: Set outputs
        id: set_outputs
        run: |
          echo "::set-output name=need-tinytex::${{ 3.1415926 }}"
      - name: echo-output
        run: |
          echo ${{ steps.set_outputs.outputs.need-tinytex }}

  getter-2-a:
    runs-on: ubuntu-latest
    needs: setter-2
    steps:
      - name: Get output
        run: |
          echo ${{ needs.setter-2.outputs.need-tinytex }}

  getter-2-b:
    runs-on: windows-latest
    needs: setter-2
    steps:
      - name: Get output
        run: |
          echo ${{ needs.setter-2.outputs.need-tinytex }}

  setter-tt:
    runs-on: ubuntu-latest
    outputs:
      need-tinytex: ${{ steps.check-if-tinytex-needed.outputs.need-tinytex }}
    steps:
      - name: Check need for TinyTex
        id: check-if-tinytex-needed
        run: |
          echo "::set-output name=need-tinytex=${{ 1 == 1 }}"

  getter-tt:
    runs-on: ${{ matrix.os }}
    needs: setter-tt
    stratety:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    steps:
      - run:
        echo ${{ needs.setter-tt.outputs.need-tinytex }}
      - run:
        if needs.setter-tt.outputs.need-tinytex == 'true'
        echo ${{ needs.setter-tt.outputs.need-tinytex }}