on: 
  - workflow_dispatch

jobs:
  tinytex-basic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-tinytex@v1
      - run: tlmgr --version
